# Direcciones IP disponibles
direcciones_ip_disponibles = []

# Asignaciones de IP a estudiantes
asignaciones_ip = {}

# Inicializar las direcciones IP disponibles (desde 192.168.0.1 hasta 192.168.0.254)
for i in range(6, 254):
    direcciones_ip_disponibles.append(f"192.168.0.{i}")


def asignar_direccion_ip(estudiante):
    # Si hay direcciones IP disponibles
    if direcciones_ip_disponibles:
        # Asignar la primera dirección IP disponible al estudiante
        direccion_ip = direcciones_ip_disponibles.pop(0)
        asignaciones_ip[estudiante] = direccion_ip
        print(f"Se asignó la dirección IP {direccion_ip} al estudiante {estudiante}")
    else:
        print("No hay direcciones IP disponibles.")

def liberar_direccion_ip(estudiante):
    # Verificar si el estudiante tiene una dirección IP asignada
    if estudiante in asignaciones_ip:
        # Liberar la dirección IP y agregarla de vuelta a las disponibles
        direccion_ip = asignaciones_ip.pop(estudiante)
        direcciones_ip_disponibles.append(direccion_ip)
        print(f"Se liberó la dirección IP {direccion_ip} del estudiante {estudiante}")
    else:
        print(f"No se encontró una dirección IP asignada para el estudiante {estudiante}")

    # Asignar la dirección IP liberada al siguiente estudiante o al estudiante que recupera la IP
    if "192.168.0.2" in direcciones_ip_disponibles:
        siguiente_estudiante = None
        for estudiante, ip in asignaciones_ip.items():
            if ip is None:
                siguiente_estudiante = estudiante
                break
        
        if siguiente_estudiante:
            nueva_direccion_ip = "192.168.0.2"
            asignaciones_ip[siguiente_estudiante] = nueva_direccion_ip
            direcciones_ip_disponibles.remove(nueva_direccion_ip)
            print(f"Se asignó la dirección IP {nueva_direccion_ip} al estudiante {siguiente_estudiante}")
        else:
            print("No hay estudiantes disponibles para asignar la dirección IP liberada.")
    else:
        print("La dirección IP 192.168.0.2 no está disponible para ser asignada.")


# Ejemplo de uso
asignar_direccion_ip("Estudiante1")
asignar_direccion_ip("Estudiante2")
asignar_direccion_ip("Estudiante3")

liberar_direccion_ip("Estudiante2")

asignar_direccion_ip("Estudiante4")
asignar_direccion_ip("Estudiante5")
asignar_direccion_ip("Estudiante6")
asignar_direccion_ip("Estudiante7")
asignar_direccion_ip("Estudiante8")
asignar_direccion_ip("Estudiante9")
asignar_direccion_ip("Estudiante10")
asignar_direccion_ip("Estudiante11")
asignar_direccion_ip("Estudiante12")
asignar_direccion_ip("Estudiante13")
asignar_direccion_ip("Estudiante14")
asignar_direccion_ip("Estudiante15")
asignar_direccion_ip("Estudiante16")
asignar_direccion_ip("Estudiante17")
asignar_direccion_ip("Estudiante18")
asignar_direccion_ip("Estudiante19")
asignar_direccion_ip("Estudiante20")
asignar_direccion_ip("Estudiante21")
asignar_direccion_ip("Estudiante22")
asignar_direccion_ip("Estudiante23")
asignar_direccion_ip("Estudiante24")
asignar_direccion_ip("Estudiante25")
asignar_direccion_ip("Estudiante26")
asignar_direccion_ip("Estudiante27")
asignar_direccion_ip("Estudiante28")
asignar_direccion_ip("Estudiante29")
asignar_direccion_ip("Estudiante30")
asignar_direccion_ip("Estudiante31")
asignar_direccion_ip("Estudiante32")
asignar_direccion_ip("Estudiante33")
asignar_direccion_ip("Estudiante34")
asignar_direccion_ip("Estudiante35")
asignar_direccion_ip("Estudiante36")
asignar_direccion_ip("Estudiante37")
asignar_direccion_ip("Estudiante38")
asignar_direccion_ip("Estudiante39")
asignar_direccion_ip("Estudiante40")
asignar_direccion_ip("Estudiante41")
asignar_direccion_ip("Estudiante42")
asignar_direccion_ip("Estudiante43")
asignar_direccion_ip("Estudiante44")
asignar_direccion_ip("Estudiante45")
asignar_direccion_ip("Estudiante46")
asignar_direccion_ip("Estudiante47")
asignar_direccion_ip("Estudiante48")
asignar_direccion_ip("Estudiante49")
asignar_direccion_ip("Estudiante50")
asignar_direccion_ip("Estudiante51")
asignar_direccion_ip("Estudiante52")
asignar_direccion_ip("Estudiante53")
asignar_direccion_ip("Estudiante54")
asignar_direccion_ip("Estudiante55")
asignar_direccion_ip("Estudiante56")
asignar_direccion_ip("Estudiante57")
asignar_direccion_ip("Estudiante58")
asignar_direccion_ip("Estudiante59")
asignar_direccion_ip("Estudiante60")
asignar_direccion_ip("Estudiante61")
asignar_direccion_ip("Estudiante62")
asignar_direccion_ip("Estudiante63")
asignar_direccion_ip("Estudiante64")
asignar_direccion_ip("Estudiante65")
asignar_direccion_ip("Estudiante66")
asignar_direccion_ip("Estudiante67")
asignar_direccion_ip("Estudiante68")
asignar_direccion_ip("Estudiante69")
asignar_direccion_ip("Estudiante70")
asignar_direccion_ip("Estudiante71")
asignar_direccion_ip("Estudiante72")
asignar_direccion_ip("Estudiante73")
asignar_direccion_ip("Estudiante74")
asignar_direccion_ip("Estudiante75")
asignar_direccion_ip("Estudiante76")
asignar_direccion_ip("Estudiante77")
asignar_direccion_ip("Estudiante78")
asignar_direccion_ip("Estudiante79")
asignar_direccion_ip("Estudiante80")
asignar_direccion_ip("Estudiante81")
asignar_direccion_ip("Estudiante82")
asignar_direccion_ip("Estudiante83")
asignar_direccion_ip("Estudiante84")
asignar_direccion_ip("Estudiante85")
asignar_direccion_ip("Estudiante86")
asignar_direccion_ip("Estudiante87")
asignar_direccion_ip("Estudiante88")
asignar_direccion_ip("Estudiante89")
asignar_direccion_ip("Estudiante90")
asignar_direccion_ip("Estudiante91")
asignar_direccion_ip("Estudiante92")
asignar_direccion_ip("Estudiante93")
asignar_direccion_ip("Estudiante94")
asignar_direccion_ip("Estudiante95")
asignar_direccion_ip("Estudiante96")
asignar_direccion_ip("Estudiante97")
asignar_direccion_ip("Estudiante98")
asignar_direccion_ip("Estudiante99")
asignar_direccion_ip("Estudiante100")
asignar_direccion_ip("Estudiante101")
asignar_direccion_ip("Estudiante102")
asignar_direccion_ip("Estudiante103")
asignar_direccion_ip("Estudiante104")
asignar_direccion_ip("Estudiante105")
asignar_direccion_ip("Estudiante106")
asignar_direccion_ip("Estudiante107")
asignar_direccion_ip("Estudiante108")
asignar_direccion_ip("Estudiante109")
asignar_direccion_ip("Estudiante110")
asignar_direccion_ip("Estudiante111")
asignar_direccion_ip("Estudiante112")
asignar_direccion_ip("Estudiante113")
asignar_direccion_ip("Estudiante114")
asignar_direccion_ip("Estudiante115")
asignar_direccion_ip("Estudiante116")
asignar_direccion_ip("Estudiante117")
asignar_direccion_ip("Estudiante118")
asignar_direccion_ip("Estudiante119")
asignar_direccion_ip("Estudiante120")
asignar_direccion_ip("Estudiante121")
asignar_direccion_ip("Estudiante122")
asignar_direccion_ip("Estudiante123")
asignar_direccion_ip("Estudiante124")
asignar_direccion_ip("Estudiante125")
asignar_direccion_ip("Estudiante126")
asignar_direccion_ip("Estudiante127")
asignar_direccion_ip("Estudiante128")
asignar_direccion_ip("Estudiante129")
asignar_direccion_ip("Estudiante130")
asignar_direccion_ip("Estudiante131")
asignar_direccion_ip("Estudiante132")
asignar_direccion_ip("Estudiante133")
asignar_direccion_ip("Estudiante134")
asignar_direccion_ip("Estudiante135")
asignar_direccion_ip("Estudiante136")
asignar_direccion_ip("Estudiante137")
asignar_direccion_ip("Estudiante138")
asignar_direccion_ip("Estudiante139")
asignar_direccion_ip("Estudiante140")
asignar_direccion_ip("Estudiante141")
asignar_direccion_ip("Estudiante142")
asignar_direccion_ip("Estudiante143")
asignar_direccion_ip("Estudiante144")
asignar_direccion_ip("Estudiante145")
asignar_direccion_ip("Estudiante146")
asignar_direccion_ip("Estudiante147")
asignar_direccion_ip("Estudiante148")
asignar_direccion_ip("Estudiante149")
asignar_direccion_ip("Estudiante150")
asignar_direccion_ip("Estudiante151")
asignar_direccion_ip("Estudiante152")
asignar_direccion_ip("Estudiante153")
asignar_direccion_ip("Estudiante154")
asignar_direccion_ip("Estudiante155")
asignar_direccion_ip("Estudiante156")
asignar_direccion_ip("Estudiante157")
asignar_direccion_ip("Estudiante158")
asignar_direccion_ip("Estudiante159")
asignar_direccion_ip("Estudiante160")
asignar_direccion_ip("Estudiante161")
asignar_direccion_ip("Estudiante162")
asignar_direccion_ip("Estudiante163")
asignar_direccion_ip("Estudiante164")
asignar_direccion_ip("Estudiante165")
asignar_direccion_ip("Estudiante166")
asignar_direccion_ip("Estudiante167")
asignar_direccion_ip("Estudiante168")
asignar_direccion_ip("Estudiante169")
asignar_direccion_ip("Estudiante170")
asignar_direccion_ip("Estudiante171")
asignar_direccion_ip("Estudiante172")
asignar_direccion_ip("Estudiante173")
asignar_direccion_ip("Estudiante174")
asignar_direccion_ip("Estudiante175")
asignar_direccion_ip("Estudiante176")
asignar_direccion_ip("Estudiante177")
asignar_direccion_ip("Estudiante178")
asignar_direccion_ip("Estudiante179")
asignar_direccion_ip("Estudiante180")
asignar_direccion_ip("Estudiante181")
asignar_direccion_ip("Estudiante182")
asignar_direccion_ip("Estudiante183")
asignar_direccion_ip("Estudiante184")
asignar_direccion_ip("Estudiante185")
asignar_direccion_ip("Estudiante186")
asignar_direccion_ip("Estudiante187")
asignar_direccion_ip("Estudiante188")
asignar_direccion_ip("Estudiante189")
asignar_direccion_ip("Estudiante190")
asignar_direccion_ip("Estudiante191")
asignar_direccion_ip("Estudiante192")
asignar_direccion_ip("Estudiante193")
asignar_direccion_ip("Estudiante194")
asignar_direccion_ip("Estudiante195")
asignar_direccion_ip("Estudiante196")
asignar_direccion_ip("Estudiante197")
asignar_direccion_ip("Estudiante198")
asignar_direccion_ip("Estudiante199")
asignar_direccion_ip("Estudiante200")
asignar_direccion_ip("Estudiante201")
asignar_direccion_ip("Estudiante202")
asignar_direccion_ip("Estudiante203")
asignar_direccion_ip("Estudiante204")
asignar_direccion_ip("Estudiante205")
asignar_direccion_ip("Estudiante206")
asignar_direccion_ip("Estudiante207")
asignar_direccion_ip("Estudiante208")
asignar_direccion_ip("Estudiante209")
asignar_direccion_ip("Estudiante210")
asignar_direccion_ip("Estudiante211")
asignar_direccion_ip("Estudiante212")
asignar_direccion_ip("Estudiante213")
asignar_direccion_ip("Estudiante214")
asignar_direccion_ip("Estudiante215")
asignar_direccion_ip("Estudiante216")
asignar_direccion_ip("Estudiante217")
asignar_direccion_ip("Estudiante218")
asignar_direccion_ip("Estudiante219")
asignar_direccion_ip("Estudiante220")
asignar_direccion_ip("Estudiante221")
asignar_direccion_ip("Estudiante222")
asignar_direccion_ip("Estudiante223")
asignar_direccion_ip("Estudiante224")
asignar_direccion_ip("Estudiante225")
asignar_direccion_ip("Estudiante226")
asignar_direccion_ip("Estudiante227")
asignar_direccion_ip("Estudiante228")
asignar_direccion_ip("Estudiante229")
asignar_direccion_ip("Estudiante230")
asignar_direccion_ip("Estudiante231")
asignar_direccion_ip("Estudiante232")
asignar_direccion_ip("Estudiante233")
asignar_direccion_ip("Estudiante234")
asignar_direccion_ip("Estudiante235")
asignar_direccion_ip("Estudiante236")
asignar_direccion_ip("Estudiante237")
asignar_direccion_ip("Estudiante238")
asignar_direccion_ip("Estudiante239")
asignar_direccion_ip("Estudiante240")
asignar_direccion_ip("Estudiante241")
asignar_direccion_ip("Estudiante242")
asignar_direccion_ip("Estudiante243")
asignar_direccion_ip("Estudiante244")
asignar_direccion_ip("Estudiante245")
asignar_direccion_ip("Estudiante246")
asignar_direccion_ip("Estudiante247")
asignar_direccion_ip("Estudiante248")
asignar_direccion_ip("Estudiante249")
asignar_direccion_ip("Estudiante250")
asignar_direccion_ip("Estudiante251")
asignar_direccion_ip("Estudiante252")
asignar_direccion_ip("Estudiante253")
asignar_direccion_ip("Estudiante254")

